# FROM ubuntu:focal
FROM lenovo-auto-delete-docker-local.artifactory.tc.lenovo.com/ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update          \
    && apt-get install -y   \
        python3-pip         \
    && pip install cpplint